### ISSUE TITLE
gVCF comparison between workflows 

### ISSUE THREAD

**Issue by yuankunzhu** [kids-first/kf-genomics-harmonization#10]

**Comment by Haoxuan-Jin** [comment]
Things that need to do : 

- [ ] prepare all the files that need to comparison.
- [ ] list all of the index/benchmarks that need to comparison.
- [ ] get familiar with RTGtools and Further understanding the output + vcfstats
- [ ] compose the script and finish the comparison.
- [ ] outcome a comparison report.

**Comment by Haoxuan-Jin** [comment]
2.5.9 **vcfstats**
Synopsis:

> Display simple statistics about the contents of a set of VCF files.

Syntax:
`$ rtg vcfstats [OPTION]... FILE+ `

Example:
```
$ rtg vcfstats /data/human/wgs/NA19240/snp_chr5.vcf.gz
Location : /data/human/wgs/NA19240/snp_chr5.vcf.gz
Passed Filters : 283144
Failed Filters : 83568
SNPs : 241595
MNPs : 5654
Insertions : 15424
Deletions : 14667
Indels : 1477
Unchanged : 4327
SNP Transitions/Transversions : 1.93 (210572/108835)
Total Het/Hom ratio : 2.13 (189645/89172)
SNP Het/Hom ratio : 2.12 (164111/77484)
MNP Het/Hom ratio : 3.72 (4457/1197)
Insertion Het/Hom ratio : 1.69 (9695/5729)
Deletion Het/Hom ratio : 2.33 (10263/4404)
Indel Het/Hom ratio : 3.13 (1119/358)
Insertion/Deletion ratio : 1.05 (15424/14667)
Indel/SNP+MNP ratio : 0.13 (31568/247249)
```

Parameters:
```
File Input/Output
--known Set to only calculate statistics for known variants.
--novel Set to only calculate statistics for novel variants.
--sample=FILE Set to only calculate statistics for the specified sample. (Default is to include all
samples). May be specified 0 or more times.
FILE+ VCF file from which to derive statistics. Use ‘-‘ to read from standard input. Must
be specified 1 or more times.
Reporting
--allele-lengths Set to output variant length histogram.
Utility
-h --help Prints help on command-line flag usage.
```

Usage:

> Use the `vcfstats` command to display summary statistics for a set of VCF files. If a VCF file contains multiple sample columns, the statistics for each sample are shown individually.

**Comment by Haoxuan-Jin** [comment]
2.5.15 **vcfeval**

Synopsis:

> Evaluates called variants for agreement with a baseline variant set irrespective of representational differences. Outputs a weighted ROC file which can be viewed with rtg rocplot and VCF files containing false positives (called variants not matched in the baseline), false negatives (baseline variants not matched in the call set), and true positives (variants that match between the baseline and calls). 
> The baseline variants might be the variants that were used to generate a synthetic simulated sample (such as via popsim, samplesim, etc), a gold-standard VCF corresponding to a reference sample such as NA12878, or simply an alternative call-set being used as a basis for comparison.

**Comment by Haoxuan-Jin** [comment]
Trying two strategies to compare two gvcf files using `vcfeval` command:

- make one gvcf file as `-b` input, another gvcf file as `-c` input
- use a public common gvcf file as `-b` input, and each gvcf that need to compare as `-c` input. Then compare the results of two `vcfeval` run.

**Comment by Haoxuan-Jin** [comment]
I think the `hap.py` from 
https://github.com/Illumina/hap.py
is also a useful tool. Maybe we can have a look on it later.

**Comment by yuankunzhu** [comment]
good find. worth a test run.
