### ISSUE TITLE
Test with a pilot run of genotype refinement workflow

### ISSUE THREAD

**Issue by yuankunzhu** [kids-first/kf-genomics-harmonization#101]

**Comment by migbro** [comment]
Completed a test run.  Test runs can be found here, with leading prefix of "refinement" https://cavatica.sbgenomics.com/u/brownm28/kf-genotype-refinement-workflow/tasks/#q
Needs to be evaluated

**Comment by yuankunzhu** [comment]
thanks. created #110 for the evaluation. close this one now
