### ISSUE TITLE
RNA-Seq Pipeline lack of a `gzip.cwl` tool.

### ISSUE THREAD

**Issue by Haoxuan-Jin** [kids-first/kf-genomics-harmonization#106]
In the `star_align_workflow.cwl` workflow, there is a step called `compressChimericJunctions`, which use the tool from `gzip.cwl`. But it's missing now.

```
  # compressChimericJunctions:
  #   run: ../../tools/gzip.cwl
  #   in:
  #     input_file: starAlign/chimeric_junctions
  #   out: [ output_file ]
```

**Comment by Haoxuan-Jin** [comment]
perhaps @yuankunzhu need to ask them about this, or we just skip this step.

**Comment by yuankunzhu** [comment]
not a block for RNA-Seq workflow. can skip this step. close this ticket.
