### ISSUE TITLE
Add another 24 samples for testing genotype refinement pipeline

### ISSUE THREAD

**Issue by migbro** [kids-first/kf-genomics-harmonization#112]
Since it's a fairly quick pipeline, @yuankunzhu has asked that I run it on some more so that our "customers" have a larger set to review and provide feedback on

**Comment by yuankunzhu** [comment]
tasks:
https://cavatica.sbgenomics.com/u/brownm28/kf-genotype-refinement-workflow/tasks/#q?page=1&status=COMPLETED
