### ISSUE TITLE
Generate QC metrics for all GH tasks

### ISSUE THREAD

**Issue by Haoxuan-Jin** [kids-first/kf-genomics-harmonization#113]

**Comment by Haoxuan-Jin** [comment]
## QC metrics were generated below:
[KF-GH-QCmetrics.xlsx](https://github.com/kids-first/kf-genomics-harmonization/files/2221758/KF-GH-QCmetrics.xlsx)

Task: `alignment-BS_KY3D0EY8-rerun2`, `alignment-BS_CC5MA1S4`, `alignment-BS_2C5JRGNT` need to re-run. @zhangb1 
`BS_2TCDZP9A` had a duplicated task, so task: `alignment-BS_2TCDZP9A-2` was removed.
`BS_1K4BZXT6` had a duplicated task, so task: `alignment-BS_1K4BZXT6-2` was removed.
`BS_R6P5VEC8` had a duplicated task, so task:  `alignment-BS_R6P5VEC8-2` was removed.

**Comment by yuankunzhu** [comment]
close this one, there're some abnormal numbers there. created #114 for investigating that

**Comment by yuankunzhu** [comment]
ask SBG for `alignment-BS_CC5MA1S4` as task COMPLETED but no aggregation metrics staged. same for `BS_2C5JRGNT `
