### ISSUE TITLE
Create workflow for speedseq sv

### ISSUE THREAD

**Issue by migbro** [kids-first/kf-genomics-harmonization#117]
Some work has been done on this already while attempting to evaluate sv2. Preliinary experience suggests that it does NOT work well with cram files.  May need to convert to bam first.

https://github.com/hall-lab/speedseq#speedseq-sv

**Comment by migbro** [comment]
Successfully created a dockerfile.  Tricky to automate as it seems it's not possible to source a file with environment vars - required for speedseq to install cnvnator.  Needed to use ENV declarations and extract from partially built image after sourcing in interactive mode the sh file that root software package suggests.  Currently in mb-speedseq branch of bixtools

**Comment by migbro** [comment]
Docker build and running sv were not straightforward, but now works smoothly
+ In docker, replaced samtools 1.3.1 with samtools 1.8 for better cram support - edited makefiles for proper path and library links
+ Also in docker omitted step the the git repo suggests to add source thisroot.sh  to speedseq.config.  This will BREAK operation of speedseq - which is just a shell script pipeline of sorts
+ In cwl, use seq_cache_populate.pl script that comes with samtools to build a REF_CACHE and export paths.  This is needed because crams rely on matching md5s with reference - paths in header of cram may not mach current locations of reference.  This process only take a minute and uses about 3GB of extra space, still faster and space-efficient over converting sam-tobam
+ cwl has js logic (some help from Avi!)  to determine and return whether secondary input file will be crai or bai

**Comment by migbro** [comment]
Tested on:
+ rabix executor
+ cwltool
+ cavatica

Eval output at some point?

**Comment by yuankunzhu** [comment]
great work. close this ticket, but it'd be nice to have a lightweight lumpy-sv wrapped when you got a chance, as that's the core part for sv of speedseq.
