### ISSUE TITLE
Create workflow for cnvator

### ISSUE THREAD

**Issue by migbro** [kids-first/kf-genomics-harmonization#118]
Copy number variation estimate tool as the title suggests.   Can be installed from here:
https://github.com/abyzovlab/CNVnator

**Comment by danria** [comment]
- CNVnator cwl: (v0.3.3, supporting CRAM input)
   https://github.com/kids-first/kf-somatic-workflow/blob/add_cnvnator/tools/cnvnator.cwl

- Run CNVnator:
   https://cavatica.sbgenomics.com/u/dangxiao/cnv-test/tasks/f1f5b366-2446-4619-8917-b4a7f5920d90/
   or
  https://cavatica.sbgenomics.com/u/dangxiao/cnv-test/tasks/867357c6-196c-4e56-b989-142fe37473a9/

**Comment by migbro** [comment]
Looks great so far!  Maybe create a branch for the docker in our bixtools d3b repo https://github.com/d3b-center/bixtools so we can use kfdrc account to hold it officially and use autobuild?
