### ISSUE TITLE
Create peddy (sp?) workflow

### ISSUE THREAD

**Issue by migbro** [kids-first/kf-genomics-harmonization#121]
to evaluate output of genotype refinement pipeline.  Will start with 30 samples test set here:
https://cavatica.sbgenomics.com/u/brownm28/kf-genotype-refinement-workflow/

**Comment by migbro** [comment]
Xiao already did this on ticket #72!  Closing this one!

**Comment by migbro** [comment]
Turns out a workflow was NOT created!

**Comment by migbro** [comment]
Created a cwl tool for peddy.  May need to evaluate whether it is to be run on it's own or as part of a bigger workflow. Can be found on cavatica:
`https://cavatica.sbgenomics.com/u/brownm28/kf-genotype-refinement-workflow/apps/#brownm28/kf-genotype-refinement-workflow/kf-peddy-tool`
on github:
`https://github.com/kids-first/kf-genotype-refinement-workflow`

**Comment by yuankunzhu** [comment]
reviewed. close this ticket now.
