### ISSUE TITLE
Compare peddy outputs

### ISSUE THREAD

**Issue by migbro** [kids-first/kf-genomics-harmonization#122]
Need to determine whether there is a difference in peddy output before and after refinement, and if so, whether it's best to run before or after refinement

**Comment by migbro** [comment]
Getting errors like:
```
2018-07-26 18:32:06 ip-10-10-4-39 peddy.peddy[16676] INFO unknown sample: BS_FJSAFZY0 in family: FM_KXC88W01
2018-07-26 18:32:06 ip-10-10-4-39 peddy.peddy[16676] INFO unknown sample: BS_K314VT4V in family: FM_KXC88W01
2018-07-26 18:32:06 ip-10-10-4-39 peddy.cli[16676] WARNING 2 samples in vcf not in ped:
BS_FJSAFZY0,BS_K314VT4V
```
When I run peddy.  My ped file looks like:
`FM_KXC88W01    BS_Z40X3HA0    BS_FJSAFZY0    BS_K314VT4V    2    2`
my vcf header (just the line with samples):
`#CHROM    POS    ID    REF    ALT    QUAL    FILTER    INFO    FORMAT    BS_FJSAFZY0    BS_K314VT4V    BS_Z40X3HA0`

Adding pedigree info to vcf and rearranging sample order in vcf to match ped file doesn't fix this warning.

**Comment by migbro** [comment]
Update on this - my input .ped file was simply not properly formatted.  I was missing additional lines for the non-proband family members

**Comment by migbro** [comment]
Genotype refinement pipeline seems to drastically affect calls on the X chromosome causing peddy to "correct" male probands to female.  Therefore, we should probably run peddy before on the vqsr vcf, and/or run on vqsr to check sex, and ignore sex-related changes when run on refinement output.

**Comment by yuankunzhu** [comment]
do you have a copy of the peddy outputs for this comparison?
