### ISSUE TITLE
Rios-Wise harmonization

### ISSUE THREAD

**Issue by migbro** [kids-first/kf-genomics-harmonization#135]
+ Need to wait on @znatty22 to get the go ahead
+ Run alignment pipe - bam2cram

**Comment by migbro** [comment]
Natasha has given the go ahead will:
+ Use the data service to get read group information - already have bs_ids and file names from an earlier validation
+ Run alignment workflow that uses FASTQ input

**Comment by migbro** [comment]
Files are currently being copied into the s3 bucket: https://s3.console.aws.amazon.com/s3/buckets/kf-study-us-east-1-prd-sd-rm8afw0r/
which is attached to volume:
https://cavatica.sbgenomics.com/v/kfdrc-harmonization/sd_rm8afw0r/
For harmonized project:
https://cavatica.sbgenomics.com/u/kids-first-drc/sd-rm8afw0r-har/

cavatica team has been notified of an odd issue where for 6 tasks, all outputs were copied, creating files with _1_ prefix:
```

**Comment by migbro** [comment]
124 files had to be recopied - some odd bug must have kept them from being exported.  Copying and tagging is complete

**Comment by allisonheath** [comment]
A long time back we delivered the unharmonized data from Hudson Alpha to the Rios group - is this in a harmonization project somewhere that we can add them to so they can get immediate access to the newly harmonized data?

**Comment by baileyckelly** [comment]
@migbro Now that we've fixed the failed sample can we look at @allisonheath comment above - getting the Rios group access to the harmonized data?

**Comment by migbro** [comment]
That right there, I have no idea yet.  @zhangb1 , @yuankunzhu what is the procedure to getting the Rios group access to the harmonized data? What is left to be done for that?

**Comment by yuankunzhu** [comment]
I think we are going to use the same project that @allisonheath created for the unharmonized data to deliver the harmonized ones. 

The project is https://cavatica.sbgenomics.com/u/kids-first-drc/hyag-6cg0/

We just need to make sure:
- [ ] make sure the metadata is updated for harmonized cram/gvcfs, @migbro can you take care of this?
- [ ] make sub-folders to hold source and harmonized files separately, I @yuankunzhu will take care of this

**Comment by yuankunzhu** [comment]
copied all Rios' harmonized data into his X01 project: https://cavatica.sbgenomics.com/u/kids-first-drc/hyag-6cg0/files. @allisonheath please review.

**Comment by allisonheath** [comment]
Looks great 👍
