### ISSUE TITLE
deliver joint-genotyping and refinement workflow result to Allison's team

### ISSUE THREAD

**Issue by zhangb1** [kids-first/kf-genomics-harmonization#146]
GH-FY15 Marazita Caucasian Trio Joint Genotyping

GH-FY15 Schiffman Trio Joint Genotyping

GH-FY15 Chung Trio Joint Genotyping

GH-FY15 Engle Trio Joint Genotyping

**Comment by yuankunzhu** [comment]
@zhangb1 how about fy16-rios and fy16-maris trio calls?

**Comment by yuankunzhu** [comment]
need to generate manifest on the fly when exporting cavatica file into kf-bucket. we will initially have all the tags for s3 converted to manifest with expanding Family ID to related Biospecimen IDs.

**Comment by zhangb1** [comment]
GH-FY15 Marazita Caucasian Trio Joint Genotyping

We don't have the refinement results for the families below:
```
FM_4G4QGRH1
FM_8WNPNTBB
FM_GAKH00GW
FM_JT5GVN3H
FM_YMK6VC74
FM_ZAT6PTE1
FM_9E3WAF2Z
FM_EWPEPFQ7
FM_PF276JVF
FM_Q1JQJBB5```

beacuse the biospecmens in those families are  having `Known Data Issues` 
from @allisonheath :
https://kidsfirstdrc.org/support/studies-and-access/#marazita

**Comment by zhangb1** [comment]
GH-FY16-Rios-Wise

There are two families : FM_1T4WR9EY and FM_JYW73WX9 
 there are some participants are missing in the family relationship.
for example: https://kf-api-dataservice.kidsfirstdrc.org/family-relationships?participant_id=PT_1AEBX8P8
PT_1AEBX8P8 has no relationship there. 

It would cause the error :https://cavatica.sbgenomics.com/u/kfdrc-harmonization/sd-rm8afw0r-01/tasks/ca2b6e01-4e94-4431-aa09-867cd8dd2c53/stats/
https://cavatica.sbgenomics.com/u/kfdrc-harmonization/sd-rm8afw0r-01/tasks/8bafb055-32f3-42ba-9cca-6aa393627a32/stats/

Bs id is not in the ped files, but in the joint-genotyping result.

**Comment by zhangb1** [comment]
study | Joint familiy vcfs
-- | --
GH-FY15-Chung | 196
GH-FY15-Engle | 270
GH-FY15-Schiffman | 305
GH-FY16-Rios-Wise | 71
GH-FY16-Maris | 459
GH-FY15-Marazita | 385
