### ISSUE TITLE
Run peddy on completed joint genotpying runs

### ISSUE THREAD

**Issue by migbro** [kids-first/kf-genomics-harmonization#148]
After Bo discovered issues with the Engle family relationships on joint genotyping, the idea of running peddy seems most relevant now.  We should run peddy after joint genotyping and before refinement, and create a summary like we do for alignments

**Comment by migbro** [comment]
Peddy has been run, and report summaries generated.  Tickets have been created on the study_imports zenhub for the data service team to double-check their ingest before we alert investigators to potential issues with sex and relation assignments

**Comment by yuankunzhu** [comment]
@migbro in your summaries, i noticed there're some errors like `CHECK_MOTHER-FATHER`, not sure what does that refer.

**Comment by yuankunzhu** [comment]
close this ticket as we finished running peddy for all the existing trio cohorts.
