### ISSUE TITLE
Expression comparison between STAR 1-pass vs 2-pass

### ISSUE THREAD

**Issue by yuankunzhu** [kids-first/kf-genomics-harmonization#159]
Run 5 samples from PBTA via toil-RNASeq workflow (1-pass) and KFDRC-RNASeq workflow (2-pass), assess the difference of the expression results.

**Comment by migbro** [comment]
May want to try and ensure we use some RNA sample from diseases with known fusion events to see if star pass 1/2 affects star-fusion calls

**Comment by zhangb1** [comment]
| X588451.1pass_FPKM | X588451.2pass_FPKM
-- | -- | --
X588451.1pass_FPKM | 1.00000 | 0.99975
X588451.2pass_FPKM | 0.99975 | 1.00000


  | X734521.1pass_FPKM | X734521.2pass_FPKM
-- | -- | --
X734521.1pass_FPKM | 1.00000 | 0.99982
X734521.2pass_FPKM | 0.99982 | 1.00000


  | X711741.1pass_FPKM | X711741.2pass_FPKM
-- | -- | --
X711741.1pass_FPKM | 1.00000 | 0.99989
X711741.2pass_FPKM | 0.99989 | 1.00000



  | X711742.1pass_FPKM | X711742.2pass_FPKM
-- | -- | --
X711742.1pass_FPKM | 1.00000 | 0.99979
X711742.2pass_FPKM | 0.99979 | 1.00000


  | X588339.1pass_FPKM | X588339.2pass_FPKM
-- | -- | --
X588339.1pass_FPKM | 1.00000 | 0.9997
X588339.2pass_FPKM | 0.9997 | 1.00000

**Comment by zhangb1** [comment]
The correlation between 1pass and 2pass in FPKM , do not have too much difference.  , the correlation coefficients are more than 0.99 among 5 test samples.

**Comment by zhangb1** [comment]
Also I got  the fusion results for those 5 samples using STAR-2pass, they all have the BRAF fusions as STAR-1pass result.

**Comment by zhangb1** [comment]
[STAR2pass_vs_1pass.pptx](https://github.com/kids-first/kf-genomics-harmonization/files/2645961/STAR2pass_vs_1pass.pptx)

Finished the comparison between 1pass and 2pass ,fusion results based on HG38. seems 2pass have less fusion result and both 1pass and 2pass have the BRAF fusions.

**Comment by zhangb1** [comment]
| X588451.1pass_FPKM | X734521.1pass_FPKM | X711741.1pass_FPKM | X711742.1pass_FPKM | X588339.1pass_FPKM
-- | -- | -- | -- | -- | --
X588451.2pass_FPKM | 0.999751557 | 0.972961147 | 0.995599273 | 0.993361009 | 0.997982528
X734521.2pass_FPKM | 0.975696159 | 0.999820694 | 0.988724777 | 0.99298145 | 0.984304099
X711741.2pass_FPKM | 0.996689258 | 0.988110693 | 0.999894539 | 0.998949605 | 0.999082661
X711742.2pass_FPKM | 0.994190444 | 0.992089275 | 0.998441887 | 0.99979472 | 0.997689031
X588339.2pass_FPKM | 0.997962999 | 0.983334853 | 0.998189025 | 0.997475463 | 0.999695119

**Comment by zhangb1** [comment]
[STAR2pass_vs_1pass.pptx](https://github.com/kids-first/kf-genomics-harmonization/files/2650148/STAR2pass_vs_1pass.pptx)
updated comparison  here , add comparison tables between all 5 samples and correlation chart between 1pass and 2pass samples

**Comment by zhangb1** [comment]
modified the FPKM use log10, and update the numbers and figures 

https://docs.google.com/presentation/d/1f-nqMSRsRS5m_9qcnDPYb2sLKyuMLAYIjkmI_Nxft68/edit#slide=id.g49aa781772_0_18

**Comment by yuankunzhu** [comment]
awesome! noticed that you have sample names in a wired way up there. think you were using R for this, R will do string converting for numbers and under score etc. no need change for this, but for future stuff and/or for your own record, you can load dataframe with `check.names=False`.

**Comment by zhangb1** [comment]
use the lastest version `STAR_2.6.1d `,using 16 threads and  output the` chimeric_junctions `results 

running two samples to do the comparsion

**Comment by zhangb1** [comment]
Also set the --outBAMsortingThreadN to 12, the running time is not changed , still cost 11 hours for 2-pass star alignment

https://cavatica.sbgenomics.com/u/zhangb1/star-2-pass-test/tasks/396c1226-9c36-40be-b041-0e67cb05e9ac/
