### ISSUE TITLE
Dependence of gVCF comparison between workflows

### ISSUE THREAD

**Issue by Haoxuan-Jin** [kids-first/kf-genomics-harmonization#16]
Things that need yuankun to assist :

- [x] prepare all the files that need to do the comparison.
path to VCF0: on the KF aws ubuntu instance: /vol/dev/yuhui/comparison_vcf/
path to VCF1: we need to re-run them
path to VCF2: https://cavatica.sbgenomics.com/u/yuankun/kf-alignment-optimization-rerun/files/#q?search=g.vcf&page=1

- [x] list all of the index/benchmarks/items that need to comparison.
apply RTGtools `vcfstats` and `vcfeval`

**Comment by yuankunzhu** [comment]
gvcf code for this task:
- VCF0: the one we received from Broad
- VCF1: the one we processed by the gatk production workflow
- VCF2: the one we processed by the optimized workflow

path to VCF0: on the KF aws ubuntu instance: /vol/dev/yuhui/comparison_vcf/
path to VCF1: we need to re-run them
path to VCF2: https://cavatica.sbgenomics.com/u/yuankun/kf-alignment-optimization-rerun/files/#q?search=g.vcf&page=1
