### ISSUE TITLE
Cavatica UI/UX Feedback gathering

### ISSUE THREAD

**Issue by yuankunzhu** [kids-first/kf-genomics-harmonization#161]
This was initially inspired by the rabix composer meeting on Nov 6th where the team gave feedbacks on RC for SBG team. We are doing another UI/UX feedback meeting with SBG team on Dec 6th. This ticket was created to gather ideas for it:

@yuankunzhu commented on [Fri Nov 30 2018](https://github.com/d3b-center/bixeng/issues/15)

- the scrabble job scheduling is not working well
- formatted font for filename
- ~dataset button name messed up~
- file limits per project
- input file limits
- top bar, it's confusion to have tab for "Projects", "Public projects" and "Controlled projects", maybe merge all into projects

**Comment by migbro** [comment]
Would like:
+ multi-select run task feature for drafted tasks

**Comment by zhangb1** [comment]
- volume page can't not show all the volumes...

![image](https://user-images.githubusercontent.com/14929845/49528638-54fb6a80-f882-11e8-9ebd-6b3e9f027e8d.png)

**Comment by yuankunzhu** [comment]
Billing account/group notification/warning. Storage will be billed monthly, we have users ran out of their piloting fund without getting any notifications, and got surprised/confused when checking their piloting account and found they own SBG moneys

**Comment by yuankunzhu** [comment]
> Moving more than 10,000 files is not supported at the moment
<img width="659" alt="screen shot 2018-12-05 at 1 07 06 pm" src="https://user-images.githubusercontent.com/4965924/49534097-b6293b00-f88e-11e8-97f2-75fa67472b5d.png">

**Comment by allisonheath** [comment]
Maybe you want to poll some of the other folks at CHOP for feedback as well (e.g. Jessica, Zalman, others?)

Feedback from Arash: email notifications off by default, when he started up his project it spammed all of the PIs that were also on the project

**Comment by yuankunzhu** [comment]
> Maybe you want to poll some of the other folks at CHOP for feedback as well (e.g. Jessica, Zalman, others?)
> 
> Feedback from Arash: email notifications off by default, when he started up his project it spammed all of the PIs that were also on the project

Think email notifications was set to be on by default. But yea, we might need to a broader survey to gather ideas later on. It was initially just an quick idea between us and Michele, let's see how this one go with them, and/or if they can actually change/update/fix anything in TAT, and then we can assess if we could do a real user survey-feedback meeting?

**Comment by zhangb1** [comment]
- In the file metadata section: the additional metadata title show up as 

![image](https://user-images.githubusercontent.com/14929845/49539452-afed8b80-f89b-11e8-9d00-4404f71d0fb7.png)
 It shows as ***Additional*** before.
