### ISSUE TITLE
Butali's harmonization project created and source file loading

### ISSUE THREAD

**Issue by zhangb1** [kids-first/kf-genomics-harmonization#162]
SD_DK0KRWK8

**Comment by zhangb1** [comment]
Just provide the cram files for now .

Use kids-first-drc create a project and import all the cram files:

https://cavatica.sbgenomics.com/u/kids-first-drc/sd-df0krwk8

**Comment by yuankunzhu** [comment]
only loaded the source files, need to do gVCF moving forward
