### ISSUE TITLE
Add missing metadata for the the existing project

### ISSUE THREAD

**Issue by zhangb1** [kids-first/kf-genomics-harmonization#164]
Add metadata to the 

**GH-CBTTC-CNMC WGS Harmonization** only in QA

https://cavatica.sbgenomics.com/u/kfdrc-harmonization/sd-bhjxbdqk-10/files/#q?page=1&file_extension=|CRAM|CRAI|CNVS|MAF

https://cavatica.sbgenomics.com/u/kfdrc-harmonization/sd-bhjxbdqk-10/files/#q?search=pass

**GH-CBTTC-PNOC WGS Harmonization** only in QA
https://cavatica.sbgenomics.com/u/kfdrc-harmonization/sd-bhjxbdqk-09/files/#q?page=1&file_extension=|CRAM|CRAI|MAF|CNVS

https://cavatica.sbgenomics.com/u/kfdrc-harmonization/sd-bhjxbdqk-09/files/#q?search=pass

**GH-PNOC Exome Alignment Harmonization**

https://cavatica.sbgenomics.com/u/kfdrc-harmonization/sd-m3dbxd12/files/#q?page=1&file_extension=|CRAI|CRAM|MAF

https://cavatica.sbgenomics.com/u/kfdrc-harmonization/sd-m3dbxd12/files/#q?search=pass

**Somatic mutations vcf files**

https://cavatica.sbgenomics.com/u/kfdrc-harmonization/sd-bhjxbdqk-07/files/#q?search=pass
https://cavatica.sbgenomics.com/u/kfdrc-harmonization/sd-bhjxbdqk-08/files/#q?search=pass

**Comment by danria** [comment]
done!
has added metadata for the above project.

- GH-CBTTC-CNMC WGS Harmonization:   
   gender | race | ethnicity for the participant is null.
   age_at_event_days:  null
   source_text_tumor_location:  null
