### ISSUE TITLE
some task seems completed but the output files are not generated

### ISSUE THREAD

**Issue by zhangb1** [kids-first/kf-genomics-harmonization#167]
For example:

https://cavatica.sbgenomics.com/u/kfdrc-harmonization/sd-bhjxbdqk-09/tasks/f3053182-a93d-4b25-8d35-45406d8f9409/

https://cavatica.sbgenomics.com/u/kfdrc-harmonization/sd-9pyzahhe-02/tasks/9b0fd563-12be-4716-96f7-b7ac5b21cbf8/

**Comment by zhangb1** [comment]
I asked sbg tech about the issues , they gave me the email below:

Hello Bo,

Our engineers checked your note and they found a issue on our side. Some of your tasks have the status COMPLETED, but they do not have all the outputs. Our engineers have resolved the issue and we expect if you re-run the tasks, they will be complete successfully.

We will refund the generated cost of all your affected tasks and I will notify you about it. Bear in mind that tasks execution did not cause additional cost. 

My apologies for the inconvenience this may caused and if you have any questions, please, do not hesitate to contact us.

Best regards,

**Comment by migbro** [comment]
outuptsweep script was added here:
https://github.com/d3b-center/study_harmonization_import
see readme in repo :)
