### ISSUE TITLE
replace CBTTC data with re-harmonized data 

### ISSUE THREAD

**Issue by yuankunzhu** [kids-first/kf-genomics-harmonization#191]
- [x] @kids-first/genomic-harmonization team will provide a list to @alubneuski for files that need to be deleted. 
- [x] @kids-first/genomic-harmonization team will load the re-harmonized data into the study bucket 
- [ ] @kids-first/genomic-harmonization team will provide a ID mapping manifest as well as the file relationship json to the study bucket

**Comment by yuankunzhu** [comment]
@alubneuski please delete all files listed on this manifest: https://github.com/kids-first/kf-cavatica-deliver/blob/master/re-harmonization/cbttc-s3-20190217.list

**Comment by alubneuski** [comment]
Removed. @yuankunzhu please confirm.

**Comment by yuankunzhu** [comment]
confirmed. close this ticket.
