### ISSUE TITLE
Input Bam file from hudsonalpha @RG issue

### ISSUE THREAD

**Issue by zhangb1** [kids-first/kf-genomics-harmonization#23]
All the bams files from hudsonalpha have the same bam header for the @\RG 
```
@RG	ID:id0    LB:lb0	PL:pl0	PU:pi0	SM:sm0
```
Also based on the manifest we have, some of the data have multiple LB id. 

The sample SM from @\RG will cause the g.vcf sample name also the same as sm0, and when we do the joint-genotyping will come into the error.

**Comment by Haoxuan-Jin** [comment]
Different `fastq` or `bam` files from one patient sample have the same `@RG`, same `ID: id0`.
This will affect the precision of `bqsr` step.
So their `@RG` should be re-name uniquely. But it can't be modified from `bam` or `cram` file.
We decide to re-run from `fastq` file with a correct `@RG` information.
