### ISSUE TITLE
Daily Standup for Sprint 2

### ISSUE THREAD

**Issue by Haoxuan-Jin** [kids-first/kf-genomics-harmonization#24]
# Daily Standup for Sprint 2
> This issue is used for record the detail of daily standup for Sprint 2. Everyone need to make a comment of what you did last day and the problem you met after the standup. (You can sign and remind the person who needs to help solve the problem that you met.)

## A Template
> Or you can make a better one.

### what I did:
- yuankun gave me the path of ru-run `g.vcf` files and I check the files.
- I used it to re-run `vcfstats` and `vcfeval`.

### problem:
- The output information of `vcfstats` of these `g.vcf` files are different and I am trying to figure out what happened.

**Comment by Haoxuan-Jin** [comment]
## 2018.04.02
### what I did:
- yuankun gave me the path of ru-run `g.vcf` files and I check the files.
- I used it to re-run `vcfstats` and `vcfeval`.

### problem:
- The output information of `vcfstats` of these `g.vcf` files are different and I am trying to figure out what happened.

**Comment by zhangb1** [comment]
- GIAB data download and analysis #9 
- kf-alignment-workflow issue  #23

**Comment by HuangXiaoyan0106** [comment]
**What I did:**
- Update the tracking items from the dataservice-api
- Compare the value of `shipment_date/volume` in _aliquot_ with the value of  `genomic_files` in _sequencing-experiment_

**Problem:**
- The logical relationship between the two values is chaotic

**Comment by sunyuhuiqw** [comment]
what I did:
1. filtering neoantigen by the alignment result of RNA sequencing data mapped to human genome
2. plotting the mutation number before/after filtering by expression data for each sample
problem:
explaining why only 45% somatic mutation can be supported by RNA seq data.

**Comment by danria** [comment]
**what I did:**
- the optimized workflow

**problem:**
- error in bwa mem
- markduplicates ?

**Comment by Haoxuan-Jin** [comment]
## 2018.04.03
### what I did:
- sprint 2 plan meeting
- NA12878 gvcf comparison.
- start to summary joint genotyping pilot report.
- re-run some failed jobs of gvcf comparison.
### problem:
- some `vcfeval` jobs are failed because memory leak, but not a block.

**Comment by HuangXiaoyan0106** [comment]
**Nothing……** 😢

**￣□￣｜｜**

**Comment by yuankunzhu** [comment]
# 2018.04.03
## what have been done:
- working on #21 clean up kf-genomics-harmonization workflows

## problem:
- none

**Comment by yuankunzhu** [comment]
## 2018.04.04
### what have been done:
- keep working on #21 clean up kf-genomics-harmonization workflows
- working on #26 #8

### problem:
- none

**Comment by Haoxuan-Jin** [comment]
## 2018.04.04
### what did I do:
- GIAB Chinese Trio data gvcf comparison.
- Finish summary joint genotyping pilot report. #4 
- Finish re-run the failed jobs of gvcf comparison and stay to make the summary report. #10 
### problem:

**Comment by zhangb1** [comment]
# 2018.04.04

What have been done:

GIAB data download and analysis #9
NA12878 PPT

**Comment by Haoxuan-Jin** [comment]
## 2018.04.05
### what did I do:
- Finish and upload joint genotyping pilot PPT report. #4 
- Finish and upload the gVCF comparison PPT report. #10 
### problem:
- A same SNP was assign to FP and FN via `vcfeval`, could be the bug of `vcfeval` method. #10

**Comment by sunyuhuiqw** [comment]
## 2018.04.05
what have I done:
finished transferring from starfusion to bedpe format

**Comment by danria** [comment]
# 2018.04.05
**what did I do:**

1. Finish my New CWLv1 workflow testing&debugging. #14

**Comment by Haoxuan-Jin** [comment]
## 2018.04.05
### what did I do:
- Open a new issue and start to work on it. #34 
- Finish it and made a result summary report. #34 
### problem:
- The `Precision` and `Sensitivity` is lower than `vcfeval` command. I check some `FP` and `FN` with eyeball, but they were truly `FP` and `FN`. #34 @yuankunzhu

**Comment by Haoxuan-Jin** [comment]
## 2018.04.10
### what did I do:
- Nothing
### problem:

**Comment by Haoxuan-Jin** [comment]
## 2018.04.11
### what did I do:
- Start to working on the workflow in the paper of ctDNA project.
### problem:
