### ISSUE TITLE
workflow tools versioning harmonization

### ISSUE THREAD

**Issue by yuankunzhu** [kids-first/kf-genomics-harmonization#27]
- [x] list harmonize tools & versions https://github.com/kids-first/kf-alignment-workflow/
- [x] build docker images https://github.com/d3b-center/bixtools
- [x] update CWL

**Comment by HuangXiaoyan0106** [comment]
## kfdrc_alignment_pipeline

### Tools in original pipeline
> picard-r:picard2.8.3-r3.3.3

> picard:2.8.3

> picard:2.15.0

- Recommend: 
    - picard: 2.15.0

> bwa-picard:broad  (BWA_VERSION 0.7.15, PICARD_VERSION 2.8.3)
- Recommend: 
    - bwa-men: 0.7.15

> verifybamid:1.0.2
- Recommend  (latest release) 
    - verifybamid: 1.1.3

> gatk:4.beta.1

> gatk:3.6-0-g89b7209
- Recommend (GATK4 stable release)
    - gatk: 4.0.0.0
> samtools:1.3.1
- Recommend  (latest release) 
    - samtools:1.8
> python:2.7.13

### Steps
- picard_revertsam:
    - tools/picard_revertsam.cwl
        - dockerPull: 'kfdrc/picard:2.8.3'
- picard_collectqualityyieldmetrics: 
    - /tools/picard_collectqualityyieldmetrics.cwl
        - dockerPull: 'kfdrc/picard:2.8.3'
- bwa_mem:
    - /tools/bwa_mem.cwl
        - dockerPull: 'kfdrc/bwa-picard:broad'
- picard_markduplicates:
    - /tools/picard_markduplicates.cwl
        - dockerPull: 'kfdrc/picard:2.8.3'
- picard_sortsam:
    - /tools/picard_sortsam.cwl
        - dockerPull: 'kfdrc/picard:2.8.3'
- verifybamid:
    - /tools/verifybamid.cwl
        - dockerPull: 'kfdrc/verifybamid:1.0.2'
- createsequencegrouping:
    - /tools/python_createsequencegroups.cwl
        - dockerPull: 'kfdrc/python:2.7.13'
- gatk_baserecalibrator:
    - /tools/gatk_baserecalibrator.cwl
        - dockerPull: 'kfdrc/gatk:4.beta.1'
- gatk_gatherbqsrreports:
    - /tools/gatk_gatherbqsrreports.cwl
        - dockerPull: 'kfdrc/gatk:4.beta.1'
- gatk_applybqsr:
    - /tools/gatk_applybqsr.cwl
        - dockerPull: 'kfdrc/gatk:4.beta.1'
- picard_gatherbamfiles:
    - /tools/picard_gatherbamfiles.cwl
        - dockerPull: 'kfdrc/picard:2.8.3'
- picard_collectaggregationmetrics:
    - /tools/picard_collectaggregationmetrics.cwl
        -  dockerPull: 'kfdrc/picard-r:picard2.8.3-r3.3.3'
- picard_collectreadgroupbamqualitymetrics:
    - /tools/picard_collectreadgroupbamqualitymetrics.cwl
        - dockerPull: 'kfdrc/picard-r:picard2.8.3-r3.3.3'
- picard_collectwgsmetrics:
    - /tools/picard_collectwgsmetrics.cwl
        - dockerPull: 'kfdrc/picard:2.15.0'
- picard_calculatereadgroupchecksum:
    - /tools/picard_calculatereadgroupchecksum.cwl
        - dockerPull: 'kfdrc/picard:2.8.3'
- samtools_coverttocram:
    - /tools/samtools_covert_to_cram.cwl
        - dockerPull: 'kfdrc/samtools:1.3.1'
- picard_intervallisttools:
    - /tools/picard_intervallisttools.cwl
        - dockerPull: 'kfdrc/picard:2.8.3'
- checkcontamination:
    - /tools/expression_checkcontamination.cwl
- gatk_haplotypecaller:
    - /tools/gatk_haplotypecaller.cwl
        - dockerPull: 'kfdrc/gatk:3.6-0-g89b7209'
- picard_mergevcfs:
    - /tools/picard_mergevcfs.cwl
        - dockerPull: 'kfdrc/picard:2.8.3'
- picard_collectgvcfcallingmetrics:
    - /tools/picard_collectgvcfcallingmetrics.cwl
        - dockerPull: 'kfdrc/picard:2.8.3'
- gatk_validategvcf
    - /tools/gatk_validategvcf.cwl
        - dockerPull: 'kfdrc/gatk:3.6-0-g89b7209'

**Comment by HuangXiaoyan0106** [comment]
## kfdrc_alignment_optimized

### Tools in optimized pipeline
> gatk:4.beta.1

> gatk:4.beta.1-3.5

- Recommend (GATK4 stable release)
    - gatk: 4.0.0.0

> picard-r:picard2.8.3-r3.3.3

> picard:2.8.3

> picard:2.15.0
- Recommend: 
    - picard: 2.15.0

> samtools:1.3.1

> samtools:1.7-11-g041220d (sbg)
- Recommend: 
    - samtools:1.8 (Latest)

> verifybamid:1.0.2
- Recommend: 
    - verifybamid: 1.1.3

> bwa-men: bwa-kf-bundle:0.1.17 (sbg)
- Recommend: 
    - bwa-men: 0.7.15

> sambamba:0.6.3 (sbg)
- Recommend: 
    - sambamba: 0.6.7 (Latest)

> python:2.7.13

### Steps
- get_bwa_threads:
    - tools/get_bwa_threads.cwl
- bwa_mem:
    - /tools/bwa_mem_samblaster_sambamba.cwl
        - dockerPull: 'images.sbgenomics.com/bogdang/bwa-kf-bundle:0.1.17'
            > old version: bwa-picard:broad
- checkcontamination:
    - /tools/expression_checkcontamination.cwl
- gatk_applybqsr:
    - /tools/gatk_applybqsr.cwl
        - dockerPull: 'kfdrc/gatk:4.beta.1'
            > done(same as old pipeline)
- gatk_baserecalibrator:
    - /tools/gatk_baserecalibrator.cwl
        - dockerPull: 'kfdrc/gatk:4.beta.1'
            > done(same as old pipeline)
- gatk_gatherbqsrreports:
    - /tools/gatk_gatherbqsrreports.cwl
        - dockerPull: 'kfdrc/gatk:4.beta.1'
            > done(same as old pipeline)
- gatk_haplotypecaller:
    - /tools/gatk_haplotypecaller_35.cwl
        - dockerPull: 'kfdrc/gatk:4.beta.1-3.5'
            > done(same as old pipeline)
- picard_calculatereadgroupchecksum:
    - /tools/picard_calculatereadgroupchecksum.cwl
        - dockerPull: 'kfdrc/picard:2.8.3'
            > done(same as old pipeline)
- picard_collectaggregationmetrics:
    - /tools/picard_calculatereadgroupchecksum.cwl
        - dockerPull: 'kfdrc/picard:2.8.3'
            > done(same as old pipeline)
- picard_collectgvcfcallingmetrics:
    - /tools/picard_collectgvcfcallingmetrics.cwl
        - dockerPull: 'kfdrc/picard:2.8.3'
            > done(same as old pipeline)
- picard_collectqualityyieldmetrics:
    - /tools/picard_collectqualityyieldmetrics.cwl
        - dockerPull: 'kfdrc/picard:2.8.3'
            > done(same as old pipeline)
- picard_collectreadgroupbamqualitymetrics:
    - /tools/picard_collectreadgroupbamqualitymetrics.cwl
        - dockerPull: 'kfdrc/picard-r:picard2.8.3-r3.3.3'
            > done(same as old pipeline)
- picard_collectwgsmetrics:
    - /tools/picard_collectwgsmetrics.cwl
        - dockerPull: 'kfdrc/picard:2.15.0'
            > done (same as old pipeline)
- picard_intervallisttools:
    - /tools/picard_intervallisttools.cwl
        - dockerPull: 'kfdrc/picard:2.8.3'
            > done(same as old pipeline)
- picard_mergevcfs:
    - /tools/picard_mergevcfs.cwl
        - dockerPull: 'kfdrc/picard:2.8.3'
            > done(same as old pipeline)
- samtools_coverttocram:
    - /tools/samtools_covert_to_cram.cwl
        - dockerPull: 'kfdrc/samtools:1.3.1'
            > done(same as old pipeline)
- verifybamid:
    - /tools/verifybamid.cwl
        - dockerPull: 'kfdrc/verifybamid:1.0.2'
            > done(same as old pipeline)
- samtools_split:
    - /tools/samtools_split.cwl
        - dockerPull: 'images.sbgenomics.com/bogdang/samtools:1.7-11-g041220d'
            > new tool
- sambamba_merge:
    - /tools/sambamba_merge.cwl
        - dockerPull: 'images.sbgenomics.com/bogdang/sambamba:0.6.3'
            > new tool
- sambamba_index:
    - /tools/sambamba_index.cwl
        - dockerPull: 'images.sbgenomics.com/bogdang/sambamba:0.6.3'
            > new tool
- sambamba_sort:
    - /tools/sambamba_sort.cwl
        - dockerPull: 'images.sbgenomics.com/bogdang/sambamba:0.6.3'
            > new tool
- picard_gatherbamfiles:
    - /tools/picard_gatherbamfiles.cwl
        - dockerPull: 'kfdrc/picard:2.8.3'
            > done(same as old pipeline)
- samtools_cram2bam:
    - /tools/samtools_cram2bam.cwl
        - dockerPull: 'images.sbgenomics.com/bogdang/samtools:1.7-11-g041220d'
            > new tool
- python_createsequencegroups:
    - /tools/python_createsequencegroups.cwl
        - dockerPull: 'kfdrc/python:2.7.13'
            > done(same as old pipeline)

**Comment by danria** [comment]
rabix run the kfdrc_alignment_wf.cwl (https://github.com/kids-first/kf-alignment-workflow/tree/master/workflows ) and updated version（https://github.com/BGI-CHOP/dangxiao/tree/master/kf-alignment-update-version/workflows) all complete;

- The test result for kfdrc_alignment_wf.cwl  : /vol/dev/dangx/test/20180420/kf-alignment-workflow_test-result

- The test result for updated version: /vol/dev/dangx/test/20180420/update_version_test_result
