### ISSUE TITLE
alignment workflow takes fastq as input

### ISSUE THREAD

**Issue by yuankunzhu** [kids-first/kf-genomics-harmonization#35]

**Comment by zhangb1** [comment]
Testing one pair  fastq as input

https://cavatica.sbgenomics.com/u/dangxiao/test-fq-input-workflow/apps/#dangxiao/test-fq-input-workflow/kf-alignment-fq-input-test

**Comment by Haoxuan-Jin** [comment]
I prepared a script for task generate, run, and monitor
https://github.com/Haoxuan-Jin/My-repository/blob/master/fq-input-workflow/fq-input-workflow.run.sh

Especially the task monitor script, I modified a lot and it can be general used on other Cavatica project.
https://github.com/Haoxuan-Jin/My-repository/blob/master/fq-input-workflow/step3-run_monitor_task/sbg_task_monitor.py

**Comment by Haoxuan-Jin** [comment]
We found that some fq files are missing is because they don’t have Aliquot id, so their BSID will not be generated. @yuankunzhu please help and fix this problem.
