### ISSUE TITLE
Harmonized Data Release

### ISSUE THREAD

**Issue by yuankunzhu** [kids-first/kf-genomics-harmonization#37]
Priority | FY | X01 | Sequencing Center | Est Release Date (NIH) | dbGaP Study ID | DRC Status
-- | -- | -- | -- | -- | -- | --
1 | 15 | Marazita Caucasian - Both Batches | WashU | V1 Released 3/22/18 via dbGaP, V2 to be released in July | phs001168 | Not Loaded
2 | 15 | Schiffman** | WashU | 11/1/17 via KF TP | phs001228 | Not Loaded
2 | 15 | Chung & Shen | Baylor | Released 5/25/17 via dbGaP | phs001110 | Not Loaded
2 | 15 | Engle | Baylor | Not yet released via dbGaP | phs001247 | Not Loaded
2 | 15 | Seidman & Gelb | Baylor | Released 11/13/17 via dbGaP | phs001138 | Not Loaded
2 | 16 | Chung*** | Broad | June 1st, 2018 via KF TP | phs001110 (would be a Version 2) | Not Loaded

Note on Marazita data: The Caucasian cohort is split into two versions and has two separate dbgap release dates. The v1 data was released via dbgap in March. The v2 data will be released this summer via the KF trusted partnership. We should harmonize both batches together for deliver to the X01, but only the v1 batch should be registered in the data service for delivery to the portal. We will register the v2 batch this summer when it is ready for release.

**Comment by baileyckelly** [comment]
Per our conversations yesterday, I've updated priorities & added some notes on Marazita.

**Comment by yuankunzhu** [comment]
close this ticket as all the listed cohorts has been harmonized.
