### ISSUE TITLE
alignment workflow metrics comparison 

### ISSUE THREAD

**Issue by yuankunzhu** [kids-first/kf-genomics-harmonization#38]
comparison items:
- [x] aggregation_metrics
- [x] wgs_metrics
- [x] gvcf_calling_metrics

project:
- original: https://cavatica.sbgenomics.com/u/yuankun/kf-alignment-rerun/
- optimized: https://cavatica.sbgenomics.com/u/yuankun/kf-alignment-optimization-rerun/

**Comment by Haoxuan-Jin** [comment]
#### The script can be found at:
https://github.com/Haoxuan-Jin/My-repository/blob/master/Get-SBG-task-information/alignment-wf-metrics.v2.py
#### Test it with some "kf" projects and "CBTTC" projects:
**kid-first:** https://github.com/Haoxuan-Jin/My-repository/tree/master/Get-SBG-task-information/kf_output
**CBTTC:** https://github.com/Haoxuan-Jin/My-repository/tree/master/Get-SBG-task-information/CBTTC_output

#### **Something can be seen from them, like:
- The `coverage` in CBTTC tasks are all `0`, then we found that there was an incorrect parameter of `BWA` in "fq-input-workflow".
- A task [alignment-BS_EN1NHWT7](https://cavatica.sbgenomics.com/u/kfdrc-harmonization/sd-46sk55a3/tasks/b3b86873-b5a4-4eab-9f52-e981b6bf26f4/) from kid-frist project don't have `wgs_metrics` file output, which is probably a bug of Cavatica.

@kids-first/genomicsharmonization please have a view on this.

**Comment by yuankunzhu** [comment]
great job. it'd be even better if you could made modifications according the the [broad-qc template](https://gist.github.com/yuankunzhu/6e04d8c324140d91cbf1eb00525cb21e), and washU
[EwingSarcoma_QC.1112samples.xlsx](https://github.com/kids-first/kf-genomics-harmonization/files/2137935/EwingSarcoma_QC.1112samples.xlsx)

**Comment by Haoxuan-Jin** [comment]
In `EwingSarcoma_QC.1112samples.xlsx`, what does:
`build id`, `instrument data count`, `instrument data ids`, `pf reads`, `freemix` mean?
In `broad-qc template`, what does:
`at_dropout`, `gc_dropout`, `gc_nc_0_19`, `haplotypes_confidently_checked`, `haplotypes_confidently_matchin`, `haplotypes_with_genotypes`, `individual_alias`, `LC-SET`, `library-1_read_pairs_examined`(9249609845/411945505 = 22), `ll_expected_sample`, `ll_no_contam`, `ll_predicted_contam`, `ll_random_sample`, `lod_expected_sample`, `PDO`, `standard_deviation`(column GC), `strand_balance`(GD), `total_clusters`(GE), `width_of_10_percent`(column HM) means.
@yuankunzhu

**Comment by yuankunzhu** [comment]
`freemix` from verifybamid step: https://genome.sph.umich.edu/wiki/VerifyBamID

**Comment by yuankunzhu** [comment]
```
instrument data count == read group counts
instrument data ids == read group ids
pf reads  == passed filter reads (this one i'm not sure)
```

**Comment by Haoxuan-Jin** [comment]
### Update script V3
https://github.com/Haoxuan-Jin/My-repository/blob/master/Get-SBG-task-information/alignment-wf-metrics.v3.py
### Output example:
[alignment-wf-all-summary-metrics.xlsx](https://github.com/kids-first/kf-genomics-harmonization/files/2156783/alignment-wf-all-summary-metrics.xlsx)

@yuankunzhu
