### ISSUE TITLE
joint genotyping pilot report

### ISSUE THREAD

**Issue by yuankunzhu** [kids-first/kf-genomics-harmonization#4]
no benchmarking included for this task, most for summary purpose

**Comment by Haoxuan-Jin** [comment]
## Plan
- [ ] Add me into Cavatica project that this pilot joint genotyping running.
- [ ] Know the detail about pipeline, samples of this pilot joint genotyping.
- [ ] List all the items that are needed in the report.
- [ ] Write and run the script to get those details.
- [ ] Summary and make a report.

**Comment by Haoxuan-Jin** [comment]
The final report is finished and shared with the link:
https://drive.google.com/open?id=1IBr9X7818JehNQnovl-wkLiPXaHCqDhB

**Comment by yuankunzhu** [comment]
@Haoxuan-Jin good job. i'm going to close this issue. but we need to do a comparison between the trio-based call vs the cohort-based call
