### ISSUE TITLE
Move CBTTC Data to KF AWS

### ISSUE THREAD

**Issue by baileyckelly** [kids-first/kf-genomics-harmonization#48]
In preparation for loading the CBTTC data into the portal, we need to move this data over to the KF AWS account. I believe this involves remapping the data in Cavatica as well to point to the files' new location. 

We will need this done before we can import the data into the production data service so that the appropriate file location is registered in Gen3. 

Note: This data set is supposed to go live in the Portal for the 5/14 Internal Review, so this will likely need to be done before that.

**Comment by yuankunzhu** [comment]
are we going to have study id for each CBTTC projects, like CBTTC-03 and CBTTC-12? or one for all. @dankolbman

**Comment by yuankunzhu** [comment]
- [ ]  study id and target bucket
- [ ]  get access

**Comment by baileyckelly** [comment]
Adding @znatty22 & @parimalak - I think we did KF7316 in QA for all of CBTTC since we're importing anything with genomic data.

**Comment by parimalak** [comment]
yes we used KF7316 in QA. I thought we are going to create stable study_id for CBTTC through data service and use it.

**Comment by yuankunzhu** [comment]
Data has been moved to KF AWS environment. CBTTC is now `SD_BHJXBDQK`, and PNOC is `SD_M3DBXD12`. close this issue
