### ISSUE TITLE
joint genotyping bigger cohort pilot 

### ISSUE THREAD

**Issue by yuankunzhu** [kids-first/kf-genomics-harmonization#5]

**Comment by zhangb1** [comment]
- [ ] define cohort

- [ ] cavatica running

**Comment by zhangb1** [comment]
Test 18 trios, 17 succeed , 1 failed

**Comment by zhangb1** [comment]
change the tool `gatk_import_genotype_filtergvcf_merge` docker image  to  **zhangb1/broad-gatk4.beta.5-picard**

all 18 trios running successfully now.

**Comment by zhangb1** [comment]
![](http://54.173.242.160/github/Rplot-ggplot.pdf)
