### ISSUE TITLE
develop workflow to take functional equivalent cram to generate gvcf

### ISSUE THREAD

**Issue by yuankunzhu** [kids-first/kf-genomics-harmonization#53]

**Comment by danria** [comment]
- workflow: https://github.com/BGI-CHOP/dangxiao/blob/master/kf-alignment-workflow-cram-gvcf/workflows/kfdrc_alignment_cram.cwl

- actually, it took 2 days to develop this workflow, put this issue in progress too early.

**Comment by yuankunzhu** [comment]
https://github.com/BGI-CHOP/dangxiao/blob/master/kf-alignment-workflow-cram-gvcf/tools/samtools_cram_reheader.cwl#L17
not sure this will work properly

**Comment by danria** [comment]
revised the samtools_cram_reheader.cwl： https://github.com/BGI-CHOP/dangxiao/commit/ada98ca7d28ab06e1a028c3e1888d2767df68c92
