### ISSUE TITLE
compare full workflow to "reheader cram -> gvcf" workflow

### ISSUE THREAD

**Issue by yuankunzhu** [kids-first/kf-genomics-harmonization#54]

**Comment by yuankunzhu** [comment]
- [ ]  choose 3 samples to do the evaluation 
- [ ]  vcfevla
- [ ]  wgs/gvcf metrics

**Comment by danria** [comment]
The Wgs Metrics and Alignment Summary Metrics:
[metrics.xlsx](https://github.com/kids-first/kf-genomics-harmonization/files/2091717/metrics.xlsx)
