### ISSUE TITLE
CWL composing of Lancet

### ISSUE THREAD

**Issue by yuankunzhu** [kids-first/kf-genomics-harmonization#61]

**Comment by Haoxuan-Jin** [comment]
#### Push a **lancet** toolkit on Cavatica
https://cavatica.sbgenomics.com/u/zhangb1/kf-somatic-tools-test/apps/#zhangb1/kf-somatic-tools-test/lancet

**Comment by Haoxuan-Jin** [comment]
But **lancet** must require a region file or bed file, which is different from others
```
$ /vol/dev/haoxuan/TumorWorkflow/lancet/lancet/lancet -h

  |                           |
  |      _` | __ \   __|  _ \ __|
  |     (   | |   | (     __/ |
 _____|\__,_|_|  _|\___|\___|\__|

Program: lancet (micro-assembly somatic variant caller)
Version: 1.0.6 (beta), April 15 2018
Contact: Giuseppe Narzisi <gnarzisi@nygenome.org>

Usage: lancet [options] --tumor <BAM file> --normal <BAM file> --ref <FASTA file> --reg <chr:start-end>
 [-h for full list of commands]

Required
   --tumor, -t              <BAM file>    : BAM file of mapped reads for tumor
   --normal, -n             <BAM file>    : BAM file of mapped reads for normal
   --ref, -r                <FASTA file>  : FASTA file of reference genome
   --reg, -p                <string>      : genomic region (in chr:start-end format)
   --bed, -B                <string>      : genomic regions from file (BED format)
```

**Comment by Haoxuan-Jin** [comment]
Run successfully on Cavatica:
https://cavatica.sbgenomics.com/u/zhangb1/kf-somatic-tools-test/tasks/227a6c96-a501-46a5-ace0-442bee53c1ee/

But need to discuss about the input region file and the output name.

**Comment by Haoxuan-Jin** [comment]
#### upload a new version to Cavatica add a region file input:
https://cavatica.sbgenomics.com/u/zhangb1/kf-somatic-tools-test/apps/#zhangb1/kf-somatic-tools-test/lancet

**Comment by Haoxuan-Jin** [comment]
#### Stable version of lancet CWL on Cavatica:
https://cavatica.sbgenomics.com/u/zhangb1/kf-somatic-tools-test/apps/#zhangb1/kf-somatic-tools-test/lancet
#### Completed task:
https://cavatica.sbgenomics.com/u/zhangb1/kf-somatic-tools-test/tasks/41f531af-8b51-4405-ba32-6a201afc7ca4/

**INPUT**

ID | Label | Type | Required | Prefix | Format
-- | -- | -- | -- | -- | --
input_normal_bam | | File | Yes |  | 
input_tumor_bam | | File | Yes |  | 
bed | | File | Yes | | 
reference | | File | Yes |  | 
output_basename | | String | Yes |  | 

**OUTPUT**

ID | Label | Type | Required | Prefix | Format
-- | -- | -- | -- | -- | --
output_vcf | | File | Yes |  |

**Comment by Haoxuan-Jin** [comment]
#### Push lancet tool to github:
https://github.com/kids-first/kf-somatic-workflow
please PR this. @yuankunzhu @zhangb1 

The only thing that need to solve now is the resource that running lancet. It seems that lots of memory and cpus are needed when running lancet with whole genome region in one task. So @zhangb1 and I suggest to run several parallel tasks with splitted bed file.

**Comment by yuankunzhu** [comment]
great! reviewing now.
