### ISSUE TITLE
KFDRC somatic workflow development 

### ISSUE THREAD

**Issue by yuankunzhu** [kids-first/kf-genomics-harmonization#62]

**Comment by danria** [comment]
The somatic workflow (Vardict, Lancet, Mutect2, strelka2)
https://cavatica.sbgenomics.com/u/zhangb1/kf-somatic-tools-test/tasks/b0c6f185-3ecd-4321-85e5-f862d324c2e0/

**Comment by danria** [comment]
The CBTTC tumor/normal cram file test:
https://cavatica.sbgenomics.com/u/zhangb1/kf-somatic-tools-test/tasks/11abfec3-11a4-4573-a1fa-d68298b876d8/
https://cavatica.sbgenomics.com/u/zhangb1/kf-somatic-tools-test/tasks/3a619901-8ac1-4a47-ae0f-ffb192d6108a/

**Comment by yuankunzhu** [comment]
So i think the basic deployment of the somatic workflow has been done. Close this ticket and opened #111 for optimization.
