### ISSUE TITLE
CBTTC tumor data harmonization to CRAM

### ISSUE THREAD

**Issue by yuankunzhu** [kids-first/kf-genomics-harmonization#63]

**Comment by yuankunzhu** [comment]
- [ ] identify tumor data
- [ ] get familiar with all the scripts @yuankun

**Comment by zhangb1** [comment]
https://cavatica.sbgenomics.com/u/kfdrc-harmonization/sd-bhjxbdqk-02

All the files are ready

**Comment by Haoxuan-Jin** [comment]
I prepared a script for task generate, run, and monitor
https://github.com/Haoxuan-Jin/My-repository/blob/master/fq-input-workflow/fq-input-workflow.run.sh

Especially the task monitor script, I modified a lot and it can be general used on other Cavatica project.
https://github.com/Haoxuan-Jin/My-repository/blob/master/fq-input-workflow/step3-run_monitor_task/sbg_task_monitor.py

**Comment by Haoxuan-Jin** [comment]
We found that some fq files are missing is because they don’t have Aliquot id, so their BSID will not be generated. @yuankunzhu please help and fix this problem.
