### ISSUE TITLE
Alignment workflow of generating CRAM only

### ISSUE THREAD

**Issue by yuankunzhu** [kids-first/kf-genomics-harmonization#64]

**Comment by Haoxuan-Jin** [comment]
This Cram workflow has been tested and ran successfully on Cavatica:
https://cavatica.sbgenomics.com/u/jinhaoxuan/kf-alignmentonly-workflow-testrun/tasks/cacd426d-77e3-4d13-9424-08d34bcc333e/

This modification has been push to the branch:
https://github.com/kids-first/kf-alignment-workflow/tree/CramOnly
