### ISSUE TITLE
load CBTTC fastq read group into kf-api-dataservice

### ISSUE THREAD

**Issue by yuankunzhu** [kids-first/kf-genomics-harmonization#65]

**Comment by zhangb1** [comment]
https://github.com/d3b-center/cbttc-bank-seq/tree/master/sqlite/initial_csv/cbttc_fastq*.csv

**Comment by zhangb1** [comment]
RG schema

```
{
"_links": "string",
"created_at": "2018-06-22T18:19:31Z",
"external_id": "string",
"flow_cell": "string",
"genomic_file_id": "string",
"kf_id": "string",
"lane_number": 0,
"modified_at": "2018-06-22T18:19:31Z",
"paired_end": 1,
"quality_scale": "Sanger"
}
```

**Comment by zhangb1** [comment]
CBTTC FQs RG info

https://docs.google.com/spreadsheets/d/1gehRr2c2yvofOssLV-3nUPS1QZbuIIRaqRkFthO8IFw/edit?usp=sharing

**Comment by zhangb1** [comment]
data service team will re-organize the RG schema

**Comment by zhangb1** [comment]
sent info to Meen , wait for him to update in data service... @liberaliscomputing

**Comment by yuankunzhu** [comment]
ok, close this ticket.

**Comment by allisonheath** [comment]
@liberaliscomputing @zhangb1 do we have a kf-study-imports ticket to reference?
