### ISSUE TITLE
run the reheader comparison pipeline

### ISSUE THREAD

**Issue by yuankunzhu** [kids-first/kf-genomics-harmonization#66]
choose 3 samples to run the whole pipeline and the reheader pipeline. 

NOTE: include the wgs metrics step

**Comment by danria** [comment]
- Choose 3 samples:
    -- GMKFC33906.cram
    -- CG0023-5294.cram
    -- GMKFC33682.cram

- The whole pipeline: (using the kf-alignment-optimized workflow)
-- GMKFC33906.cram: https://cavatica.sbgenomics.com/u/yuankun/kf-alignment-optimization-rerun/tasks/46298240-aef6-4dd8-911d-a1557347a5bd/
-- CG0023-5294.cram: https://cavatica.sbgenomics.com/u/yuankun/kf-alignment-optimization-rerun/tasks/c2319241-c0e5-42f3-8db5-7cc2119ae3e1/
-- GMKFC33682.cram: https://cavatica.sbgenomics.com/u/yuankun/kf-alignment-optimization-rerun/tasks/a5d461ea-5292-45e8-9a4c-abfd864aec32/

- The reheader pipeline: (using the kfdrc-cram-reheader workflow)
-- GMKFC33906.cram: https://cavatica.sbgenomics.com/u/dangxiao/test-cram-reheader-workflow/tasks/05f79170-c1fd-4b6e-9251-0095283bd101/
-- CG0023-5294.cram: https://cavatica.sbgenomics.com/u/dangxiao/test-cram-reheader-workflow/tasks/a79b87fc-aa37-4f90-b669-a56f19789e4d/
-- GMKFC33682.cram: https://cavatica.sbgenomics.com/u/dangxiao/test-cram-reheader-workflow/tasks/8c9069f0-b349-44e4-be35-93fa6caf231d/

**Comment by yuankunzhu** [comment]
@genomicsharmonization hi team, please review
