### ISSUE TITLE
gvcf comparison for output from full/reader pipelines

### ISSUE THREAD

**Issue by yuankunzhu** [kids-first/kf-genomics-harmonization#67]

**Comment by Haoxuan-Jin** [comment]
Use optimized result as baseline to compare with reheader result:

ID | Precision | Recall | F-measure
-- | -- | -- | --
CG0023-5294 | 99.55% | 99.52% | 99.54%
GMKFC33682 | 99.52% | 99.43% | 99.48%
GMKFC33906 | 99.49% | 99.44% | 99.47%
