### ISSUE TITLE
SV2: Structural Variation Genotyper

### ISSUE THREAD

**Issue by yuankunzhu** [kids-first/kf-genomics-harmonization#69]
investigate/assess https://github.com/dantaki/SV2

**Comment by migbro** [comment]
Evaluate this tool, we don't have an SV in any of our pipelines as of yet

**Comment by migbro** [comment]
Some notes on progress:
+ pip install cython first, then the sv2 package
+ oddly, fasta reference can't use reference on other mount, need to copy locally
+ input vcf needs to be split into snps and indel/other structural variants in not already.  I used vcftools
+ sv vcf (vcf with indels) needs SNTYPE= and END= INFO fields.  trying to see if snpEff will do that
+ if above works, recommend vcftools pipe directly into snpEff OR annotate whole thing first

**Comment by migbro** [comment]
This development will be on hold as it requires a tool like speedseq sv to have structural variants called before genotyping

**Comment by migbro** [comment]
blocker for this mostly cleared, successfully ran locally using a docker build on test crams with lumpy-sv output.  need to test on full crams and also evaluate outputs

**Comment by migbro** [comment]
Runs on cwltool, rabix executor, and cavatica.  Completed a test run here:
https://cavatica.sbgenomics.com/u/brownm28/kf-genotype-refinement-workflow/tasks/bc8691df-93ae-4984-8b29-6e930ebf5b9c/
outputs need evaluation
