### ISSUE TITLE
CWLv1 composing for optimized workflow

### ISSUE THREAD

**Issue by yuankunzhu** [kids-first/kf-genomics-harmonization#7]
- [ ] BAM Preprocessing:  picard_revertsam   --->    samtools_cram2bam + samtools_split

- [ ] Marking duplicates, sort:  picard_markduplicates + picard_sortsam  --->  sambamba_merge + sambamba_sort

**Comment by bogdang989** [comment]
This chages are merged to https://github.com/kids-first/kf-alignment-workflow master branch. I will close the issue, as suggested by @yuankunzhu
