### ISSUE TITLE
cavatica metadata for kfdrc harmonized files

### ISSUE THREAD

**Issue by yuankunzhu** [kids-first/kf-genomics-harmonization#70]

**Comment by Haoxuan-Jin** [comment]
Result files after kfdrc harmonization workflow don't have any metadata in it.
We should discuss and decide what kind of metadata that we should add.
These metadata should have a standard.

**Comment by danria** [comment]
- The program to add cavatica metadata:
https://github.com/BGI-CHOP/dangxiao/blob/master/API_Python/metadata_file.py

- have tested on cavatica
