### ISSUE TITLE
Make peddy available for KFDRC

### ISSUE THREAD

**Issue by yuankunzhu** [kids-first/kf-genomics-harmonization#72]
https://github.com/brentp/peddy

**Comment by yuankunzhu** [comment]
to run peddy, i think we need the inputs from the data-service team in terms of providing the pedigree files

**Comment by danria** [comment]
1. peddy introduction

- peddy compares familial-relationships and sexes as reported in a PED/FAM file with those inferred from a VCF.

- estimate relatedness, IBS0, heterozygosity, sex and ancestry. 

 2. FAM file format:

    A text file with no header line, and one line per sample with the following six fields:

- Family ID ('FID')
- Within-family ID ('IID'; cannot be '0')
- Within-family ID of father ('0' if father isn't in dataset)
- Within-family ID of mother ('0' if mother isn't in dataset)
- Sex code ('1' = male, '2' = female, '0' = unknown)
- Phenotype value ('1' = control, '2' = case, '-9'/'0'/non-numeric = missing data if case/control)

3. Installation
git clone https://github.com/brentp/peddy
cd peddy
pip install -r requirements.txt
pip install --editable .

4. test example

- family: https://cavatica.sbgenomics.com/u/kfdrc-harmonization/sd-9pyzahhe-09/tasks/12b6a32f-78cf-46e0-b593-a9aae65e7fde/
- Run:
python3 -m peddy -p 4 --sites hg38 --prefix FM_HCT2R6B6 --plot 12b6a32f-78cf-46e0-b593-a9aae65e7fde.vcf.gz 12b6a32f-78cf-46e0-b593-a9aae65e7fde.fam   

  ---use 4 cpus to run 
  ---need the vcf file index
  ---By default, peddy uses hg19/GRCh37. It can be forced to use sites for hg38 by passing --sites hg38. 
- peddy html result:
https://cavatica.sbgenomics.com/u/zhangb1/kf-somatic-tools-test/files/5b2c09deec70495356f8b253/

  -- The results have 4 csv files and 4 static QC plots that mirror those in the interactive html. These will indicate:
    --- discrepancies between ped-reported and genotype-inferred relations
    --- discrepancies between ped-reported and genotype-inferred sex
    --- samples with higher levels of HET calls, lower depth, or more variance in b-allele-frequency (alt / (ref + alt )) for het calls.
    --- an ancestry prediction based on projection onto the thousand genomes principal components
