### ISSUE TITLE
Compose fq-input-CramOnly-workflow

### ISSUE THREAD

**Issue by Haoxuan-Jin** [kids-first/kf-genomics-harmonization#76]

**Comment by Haoxuan-Jin** [comment]
#### Update  a new workflow:
https://cavatica.sbgenomics.com/u/jinhaoxuan/kf-alignmentonly-workflow-testrun/apps/#jinhaoxuan/kf-alignmentonly-workflow-testrun/kfdrc-alignment-fqinput-cram-only-wf
#### Test it with some data: 
https://cavatica.sbgenomics.com/u/jinhaoxuan/kf-alignmentonly-workflow-testrun/tasks/5290a9e4-74da-4382-b279-47498f027b29/

**Comment by Haoxuan-Jin** [comment]
#### The workflow is complete and push to [kids-first/kf-alignment-workflow](https://github.com/kids-first/kf-alignment-workflow)
@kids-first/genomicsharmonization please have a look and @yuankunzhu @zhangb1 please PR this:
https://github.com/kids-first/kf-alignment-workflow/pull/69

**Comment by yuankunzhu** [comment]
reviewed. I think the job was done nicely. but there're some potential naming conventions i think we should address at a latter stage. opened ticket #85 to hold the discussions there. close this one now.
