### ISSUE TITLE
GH-FY16 Seidman Alignment Harmonization

### ISSUE THREAD

**Issue by zhangb1** [kids-first/kf-genomics-harmonization#77]

**Comment by allisonheath** [comment]
The current plan for this is to have the biospecimen IDs in the data service soon so you will be able to use them in your harmonization.

**Comment by zhangb1** [comment]
Cavatica project:
https://cavatica.sbgenomics.com/u/kfdrc-harmonization/sd-preasa7s-01/

Total 1248 cram files need to be harmonized . Only generate the gvcf files.

**Comment by zhangb1** [comment]
Finished running one task found the HC cost 6 hours and picard rename cost 40 mins. 

@migbro is testing the new modified workflow to save more time.  Using cram as printreads input and bam as output to the HC , and own python script to rename the gvcf instead of the picard rename.

**Comment by zhangb1** [comment]
Harmonization is done on cavatica. 

https://cavatica.sbgenomics.com/u/kfdrc-harmonization/sd-preasa7s-01/tasks/#q
