### ISSUE TITLE
Match CBTTC files between kf-data-servies and cavatica dataset

### ISSUE THREAD

**Issue by Haoxuan-Jin** [kids-first/kf-genomics-harmonization#79]

**Comment by Haoxuan-Jin** [comment]
[ ] wait for Meen upload new data set.
[ ] get manifest information.
[ ] compare and match samples&files between two table.

**Comment by zhangb1** [comment]
Trying to get the data from QA, got some problem about the `analyte_type`. Meen is working on these now.

Meen Chul Kim [12:57 PM]
 Got QC from Bo that using `external_sample_id` cannot uniquely distinguish biospecimens if one sample goes into different sequencing processes such as `DNA` and `RNA`. Will add `experiment_strategy` chained by dot to `external_sample_id` and reload `biospecimen` in QA >> Adding `acls` to GFs in QA >> Reloading BS, SE, and GF in PRD.

**Comment by zhangb1** [comment]
https://cavatica.sbgenomics.com/d/cavatica/cbttc-mb-pa-02/files/57fff1c6e4b0144f66f0b968/

This file is missing in Dataset and data server. Need to import.

**Comment by zhangb1** [comment]
All the Germline  FQ files and BS ID:

https://docs.google.com/spreadsheets/d/1Dt8cFNp2ncLLBQ3g33uYhV1l4SdEmZd1FnPI3UaLm08/edit?usp=sharing

**Comment by zhangb1** [comment]
All Tumor FQ files and BS IDs:

https://docs.google.com/spreadsheets/d/1ez4sdBl33a-lFtfZntAvLGVe7OMv1acQCULulLwnPtc/edit?usp=sharing

```
7316-99T2_232B_S2_L002_R2_001.fastq.gz   BS_XYPG1SXC
```
This file is missing, just skip this  `BS_XYPG1SXC` sample for now.

**Comment by zhangb1** [comment]
Update the missing file to the cavatica project

https://cavatica.sbgenomics.com/u/kfdrc-harmonization/sd-bhjxbdqk-05/files/#q?search=7316-99T2&page=1
@Haoxuan-Jin can run this sample now
