### ISSUE TITLE
genomics harmonization execution & operation automatization

### ISSUE THREAD

**Issue by yuankunzhu** [kids-first/kf-genomics-harmonization#81]

**Comment by zhangb1** [comment]
script to get he study id and information we need  to run the harmonization project

**Comment by zhangb1** [comment]
All the tools and script will update here:

https://github.com/d3b-center/kf-har-execution-tools

**Comment by zhangb1** [comment]
The **all-run.py** tool will generate the draft tasks for the project .

How to Run the tasks and monitor the tasks refer to the issue #55
