### ISSUE TITLE
Make Plink available for GH group

### ISSUE THREAD

**Issue by yuankunzhu** [kids-first/kf-genomics-harmonization#82]
http://zzz.bwh.harvard.edu/plink/

**Comment by danria** [comment]
1. Plink IBS/IBD: http://zzz.bwh.harvard.edu/plink/ibdibs.shtml#genome

2. download: https://www.cog-genomics.org/plink2 

3. Run
 -  vcf file to ped file
plink --vcf 12b6a32f-78cf-46e0-b593-a9aae65e7fde.vcf.gz --maf 0.01 --geno 0.1 --recode --out FM_HCT2R6B6

    --maf： only include SNPs with MAF >= 0.01. 
    --geno： To include only SNPs with a 90% genotyping rate (10% missing) use
    The basic option to generate a new dataset is the --recode option
    --out {filename} 

-  IBS/IBD  estimation
    plink --file FM_HCT2R6B6 --out IBD --genome
    
    generate the *.genome file

4. example result (FM_HCT2R6B6)

     https://drive.google.com/drive/folders/1-sExL5STItDz1m-PR0MZUXI-9G69geo-?usp=sharing
