### ISSUE TITLE
Get task information from Marazita's sample

### ISSUE THREAD

**Issue by Haoxuan-Jin** [kids-first/kf-genomics-harmonization#86]
get `Reads Num`, `coverage`, and `AvgReadLength` information.

**Comment by Haoxuan-Jin** [comment]
Made a table content `filename`, `alignment software`, `Reads Num`, `coverage`, `AvgReadLength`.

[Marazita.taskinfo.xlsx](https://github.com/kids-first/kf-genomics-harmonization/files/2120860/Marazita.taskinfo.xlsx)

**Comment by yuankunzhu** [comment]
great! just send it to @fiendish . close this.

**Comment by fiendish** [comment]
Per an email I just sent, I also need the numbers for 

4955f993-f969-4a19-9310-c9819abc0d3c.cram
7525875a-9d8d-4251-9ab5-7252c6b6a434.cram
b1256011-098e-4ad8-9889-1f7b045e7ba4.cram
ef81be54-8dff-41c5-b6ae-c47b579861ae.cram
2bbc6944-8695-4c26-b59f-608ae014def4.cram
e02a1579-abb6-4522-82df-fd473694dc82.cram

**Comment by Haoxuan-Jin** [comment]
I think this issue is finished. So I close it
