### ISSUE TITLE
QC & Deliver Marazita trio and cohort joint genotyping

### ISSUE THREAD

**Issue by yuankunzhu** [kids-first/kf-genomics-harmonization#87]
The Marazita V2 trio-based and enter caucasian cohort based joint genotyping has both been completed. Now we need to QC the process:
  - external sample ID, family ID, participate ID and biospecimen IDs are all matched @zhangb1 
  - for cohort based JG call, do we keep all 1333 samples, or we should take some of them off. @yuankunzhu 
  - for incomplete families, generate the list, share with marazita's group before we kickoff any runs @yuankunzhu

**Comment by zhangb1** [comment]
Marazita Incomplete Families list

https://docs.google.com/spreadsheets/d/1gZD_l39S1beJjaA8Qnk2sKa7u4hnHUKwbbgwHOgYVn4/edit?usp=sharing

**Comment by zhangb1** [comment]
Marazita family  trio based analysis

- Total 484 family information in data service.

- First batch 331 family trios.

- Second batch 64 family trios.

- 89 incomplete families in total

**Comment by yuankunzhu** [comment]
IDs list at https://docs.google.com/spreadsheets/d/1gZD_l39S1beJjaA8Qnk2sKa7u4hnHUKwbbgwHOgYVn4/edit?usp=drive_web&ouid=113560694089186864567

close this ticket.
