### ISSUE TITLE
benchmarking with GIAB data

### ISSUE THREAD

**Issue by yuankunzhu** [kids-first/kf-genomics-harmonization#9]

**Comment by zhangb1** [comment]
Data Download：

https://github.com/genome-in-a-bottle/giab_data_indexes

**Comment by zhangb1** [comment]
Cavatica project:

https://cavatica.sbgenomics.com/u/zhangb1/giab-project/

**Comment by zhangb1** [comment]
Using cavatica public app `vbt` to run the comparison 

https://cavatica.sbgenomics.com/u/yuankun/variant-comparison-tool

**Comment by zhangb1** [comment]
Report 
https://docs.google.com/presentation/d/1vNuJo_lRWxKG5ap7SE9y1BoHMNKpcFX26TKNd8TjrF8/edit#slide=id.p3
