### ISSUE TITLE
CWL composing for CalculateGenotypePosteriors

### ISSUE THREAD

**Issue by yuankunzhu** [kids-first/kf-genomics-harmonization#91]

**Comment by migbro** [comment]
Struggling a bit with the last step in the workflow.  GATK3 outlines tools and parameters.  GATK4 has the same, but in either version VariantAnnotator tool requires ped file input, but fails to recognize/needs another parameter that is difficult to ascertain.  Example, w/out pedigree file:
```WARN  PossibleDeNovo - Annotation will not be calculated, must provide a valid PED file (-ped) from the
 command line.```
With pedigree file:
```A USER ERROR has occurred: Pedigree argument "pedigree" or "founder-id" was specified without a pedigree annotation
being requested, (eg: ))```

**Comment by migbro** [comment]
Yuankun agrees that the above issue is a gatk4 bug. For the time being, for the PossibleDeNovo step, will use gatk 3.78

**Comment by migbro** [comment]
Created and run successfully locally and on cavatica.  Can be found here for review:
```
https://github.com/migbro/kf-gentoype-refinement-workflow
```
