### ISSUE TITLE
BS_XYPG1SXC one fastq file is missing 

### ISSUE THREAD

**Issue by zhangb1** [kids-first/kf-genomics-harmonization#94]
7316-99T2_232B_S2_L002_R2_001.fastq.gz  is missing in cavatica datasets and data service
need to be imported.

**Comment by allisonheath** [comment]
I don't see this in the CHOP AWS bucket - did it not get transferred over from UPenn?

**Comment by zhangb1** [comment]
@allisonheath 
The missing file is in the UPenn aws s3 bucket:
s3://cbttc.seq.data/Curran_medulloblastoma_8_pairs_human.WGS/7316-99T2/7316-99T2_232B_S2_L002_R2_001.fastq.gz

**Comment by allisonheath** [comment]
Looks like it wasn't in the original copy/remap manifest that was generated @alubneuski @yuankunzhu ?

**Comment by yuankunzhu** [comment]
no. it got somehow slipped off. we need to add it back
