### ISSUE TITLE
RNA-Seq Pipeline Deploy on Cavatica

### ISSUE THREAD

**Issue by yuankunzhu** [kids-first/kf-genomics-harmonization#95]
Bring GDC RNA-Seq workflow into Cavatica/Rabix

**Comment by Haoxuan-Jin** [comment]
it is now block by #106

**Comment by Haoxuan-Jin** [comment]
First version of RNA-seq workflow
https://cavatica.sbgenomics.com/u/zhangb1/kf-rnaseq-workflow-test/apps/#zhangb1/kf-rnaseq-workflow-test/kf-rnaseq-wf

**Comment by yuankunzhu** [comment]
related ticket: https://github.com/d3b-center/bixeng/issues/28
