### ISSUE TITLE
Validate somatic caller output

### ISSUE THREAD

**Issue by migbro** [kids-first/kf-genomics-harmonization#99]
Ensure vcf output between somatic callers are consistent, or if not, account for it if needed, i.e. repetitive/adjacent indels

**Comment by migbro** [comment]
Haoxuan will run his pipeline on a handful of samples, I will likely use bedtools to look for perfect overlap and "mismatched" called.  I'll see if mismatched calls overlap or are within a few bp of each other and take a look at the alignments using IGV to get a sense of what is going on.

**Comment by migbro** [comment]
Using bedtools closest can already see a few odd instances between lancet and mutect, for example:
```
chr1:122903210-122903214
TCGTT # REF
  T   # Mutect2
   C  # Lancet
chr22:18,094,784-18,094,792
TTCTTTTTT   # REF
 TTTCTTC     # Lancet
  CTTCT      # Mutect2
  T

chr1:42635603-42635610
ATTGAGAC # REF
 TCGAGAC # Lancet
  C      # Mutect2
```
will want to review bam...

**Comment by migbro** [comment]
General notes:
  * Vardict outputs EVERYTHING - somatic and germline calls
  * Mutect does not use PASS and REJECT, just '.' (dot) for pass, and a reason for reject
  * Strelka and lancet have very few, if any conflicts in calls
  * Mutect and vardict have the most.  Notable difference is that mutli-bp substitutions are split with each bp as a line, vardict clusters as one
  * Mutect and vardict even at MODERATE and HIGH impact calls, have discrepncies as to the change at the same position, as well as when within one of each other (like in previous point).  Could make it tricky to harmonize calls

**Comment by migbro** [comment]
May need some further review later.  Output comparisons are in my s3 bucket, in `data-bucket/dev-data/miguel/vcf_check`.
Tumor cram: `a2e43f35-5ee5-4bf7-8d74-35f18d99668f.cram`
Normal cram: ` 50c92f84-b27b-480d-9f1f-0967609aed35.cram`
Found on cavatica, in project `zhangb1/kf-somatic-tools-test`

**Comment by yuankunzhu** [comment]
nice insight, close this one now.
